### ISSUE TITLE
errant word in question statement

### ISSUE THREAD

**Issue by alanczeme** [learn-co-curriculum/phase-1-quiz-javascript-events#1]
### Canvas Link

https://learning.flatironschool.com/courses/4985/quizzes/25999/take/questions/168651

### Concern

`The JavaScript code able would throw an error.`

remove "able"

**Comment by lizbur10** [comment]
Hi @alanczeme ! Thanks for bringing this to our attention - the error has now been fixed.

Thanks for contributing to the Flatiron School curriculum 💙
