### ISSUE TITLE
Source material doesn't cover answer

### ISSUE THREAD

**Issue by zlefler** [learn-co-curriculum/phase-1-quiz-javascript-events#2]
### Canvas Link

https://learning.flatironschool.com/courses/4978/quizzes/26872

### Concern

Hey there!
In the final question in this quiz, it asks which of four code options will select the input info from the form. When I didn't get it fully right, the suggested source to learn the answer is in the video "Forms" :https://learning.flatironschool.com/courses/4978/pages/video-forms?module_item_id=362199

However, in the video, she gives one example of how to do it, without explaining the others. I didn't feel that I was really able to answer that question from the material provided.

That's all, thanks!

**Comment by lizbur10** [comment]
Hi @Leavingvalhalla! Thanks for bringing this to our attention. We have added a second source that covers the material that wasn't covered in the link video lesson.

Thanks for contributing to the Flatiron School curriculum 💙
