### ISSUE TITLE
JavaScript Events Quiz - Question 9 - Submitted the Correct Answer but Counted Incorrect

### ISSUE THREAD

**Issue by jmacapagal90** [learn-co-curriculum/phase-1-quiz-javascript-events#4]
### Canvas Link

https://learning.flatironschool.com/courses/5192/quizzes/30397/history?version=2

### Concern

I submitted the right answer to Question 9 of JavaScript Events Quiz (see my 1st two attempts), and it was counted wrong. 

### Additional Context

[James Macapagal (He_Him)'s Quiz History_ JavaScript Events Quiz - attempt 2.pdf](https://github.com/learn-co-curriculum/phase-1-quiz-javascript-events/files/8755724/James.Macapagal.He_Him.s.Quiz.History_.JavaScript.Events.Quiz.-.attempt.2.pdf)
[JavaScript Events Quiz_ Phase 1.pdf](https://github.com/learn-co-curriculum/phase-1-quiz-javascript-events/files/8755725/JavaScript.Events.Quiz_.Phase.1.pdf)

**Comment by lizbur10** [comment]
Hi @jmacapagal90 ! It looks like the reason it was marked wrong is that the acceptable answers all have a space between the  comma and the `logSubmit`. This is a flaw in the question and we have fixed it, but the update may not show in your Canvas course. If you still have a third try, adding the space should get you credit for correctly answering the question 💙
