### ISSUE TITLE
JavaScript Events Quiz

### ISSUE THREAD

**Issue by samperozek** [learn-co-curriculum/phase-1-quiz-javascript-events#6]
I submitted the correct answer for Question #9 but it counted it as incorrect.

**Comment by lizbur10** [comment]
Hi @samperozek - sorry to hear that! Can you please provide more detail for me? I'll need the text of the question as well as exactly what you submitted as the answer.

Thanks!

**Comment by lizbur10** [comment]
Hi @samperozek. Without additional information I'm unable to do anything about this, so I'm going to go ahead and close the issue. If you are able to provide the text of the question and what you entered as the answer, feel free to reopen it 💙
