### ISSUE TITLE
Answered question correctly but still was graded incorrectly

### ISSUE THREAD

**Issue by conlonsp** [learn-co-curriculum/phase-1-quiz-javascript-events#7]
### Canvas Link

https://learning.flatironschool.com/courses/5300/quizzes/29420

### Concern

<img width="1728" alt="Screen Shot 2022-07-17 at 7 01 08 PM" src="https://user-images.githubusercontent.com/105941741/179428274-457b93bc-9033-4bd5-882e-c7e95b1e727a.png">

### Additional Context

I answered question 10 correctly on the JavaScript Events Quiz, but due to the slight differences in syntax provided as correct answers, my answer was deemed wrong. 
<img width="1728" alt="Screen Shot 2022-07-17 at 7 01 08 PM" src="https://user-images.githubusercontent.com/105941741/179428321-8a8eca70-3733-4dfb-b54d-33077de2d03e.png">

**Comment by lizbur10** [comment]
Hi @conlonsp ! Thanks for bringing this to our attention. The question has now been updated to account for the missing syntax options.

Thanks for contributing to the Flatiron School curriculum 💙
